# Generated by Django 4.2.6 on 2025-03-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
