# Generated by Django 4.2.6 on 2025-03-10 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryCode',
            fields=[
                ('code_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='entry_code', to='users.user')),
            ],
            options={
                'db_table': 'entry_codes',
            },
        ),
    ]
