# Generated by Django 4.2.6 on 2025-04-03 16:25

import apps.photos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='photo_path',
        ),
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.photos.models.user_directory_path),
        ),
    ]
