# Generated by Django 4.2.6 on 2025-04-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_remove_photo_photo_path_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
