# Generated by Django 4.2.6 on 2025-04-14 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_fname_remove_user_lname'),
        ('photos', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFaceEncoding',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='face_encoding', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('encoding', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_face_encoding',
            },
        ),
    ]
